modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId = "sns"
version = "${file.jarVersion}"
displayName = "Sacks 'N Such"
logoFile = "icon.png"
authors = "Traister101"
description = '''An addon for TFC focusing on bringing vessel like handheld containers for all your adventuring needs'''

[[dependencies.sns]]
modId = "tfc"
mandatory = true
versionRange = "[3.1.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sns]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sns]]
modId = "curios"
mandatory = false
versionRange = "[5.4.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sns]]
modId = "esc"
mandatory = true
versionRange = "[1.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[mc-publish]
dependencies = [
	"tfc@3.1.9{modrinth:JaCEZUhg}",
	"curios@5.4.5{modrinth:vvuO3ImH}"
]